= lb1344-bring-in-your-own-knowledge-to-openshift-lightspeed-and-rag-pipeline

This content was delivered as part of the Red Hat Summit in 2025. If you wish to
try to experience this content on your own, you will need a working installation
of OpenShift Container Platform along with OpenShift Lightspeed. 

Note that this lab used a preview build of the OpenShift Lightspeed 0.3.4
release, but the instructions should work with 0.3.4 or newer OpenShift
Lightspeed environments.

Further, you will have to expose your own OpenShift registry via a route in
order to push the RAG content image. Alternatively, you could push to your own
Quay or other container registry.


== Displaying the content

You can use Podman to display this lab's content. First, clone this repository,
and then change to the directory where you cloned this content. Then, run
Podman:

+
[source,sh]
----
podman run --rm --name antora -v $PWD:/antora -p 8080:8080 -i -t ghcr.io/juliaaano/antora-viewer
----

For SELinux environments, `:z` may need to be appended to the volume mount:

[source,sh]
----
podman run --rm --name antora -v $PWD:/antora:z -p 8080:8080 -i -t ghcr.io/juliaaano/antora-viewer
----

Follow the instructions for accessing the web server that are displayed in the
Podman output.