= Add Your Knowledge
Most organizations that have been using OpenShift Container Platform for any
length of time have developed their own policies, procedures, templates, and
other organizationally-specific information about OpenShift.

As you learned earler, OpenShift Lightspeed only uses the OpenShift
documentation to support answers by default. So, how can you get your important
internal knowledge into the system? Well, there's a process for that.

NOTE: This is currently a Technology Preview feature of OpenShift Lightspeed. 
The method of using `podman` to build and push a RAG database from local
markdown files is just a first draft and will be replaced by a more
sophisticated system in the future. If this feature is important to you, please
take time to talk to us after the lab or schedule a meeting to discuss your
particular scenarios.

== Examine the documentation
In the web terminal, you can SSH into a system that already has ACME's internal
documentation downloaded.

xx

The documentation is located in the `byok` folder, and, right now, consists of 
just two documents:

* the specific ACME process for horizontal pod autoscaling
* the specific ACME process for adding GPU nodes

Take a look at those files using `cat`, `less`, or your favorite tool to get
an understanding of what they are discussing.

== Build the RAG database
In the architecture slide, you saw how OpenShift Lightspeed used a RAG database
inside the server that provided the relevant documentation to support user 
questions. Now, you will use a `podman`-based process to build another RAG
database image that you will then tell OpenShift Lightspeed to use.

Building the RAG database is pretty trivial, as we have provided a pre-packaged
container image with the required software.

NOTE: If you have an extreme amount of internal documentation, the database
creation process could take several minutes, as it involves a
computationally-intensive process called _embedding_. GPUs can improve this
time, but you are unlikely to be using this process very often (unless your
internal documentation is changing very frequently).

Make sure to change your directory as follows:

xx

Then, run the following `podman` command to build the database:

  podman run -e OUT_IMAGE_TAG=latest -it --rm --device=/dev/fuse \
	-v <dir_tree_with_markdown_files>:/markdown:Z \
	-v <dir_for_image_tar>:/output:Z \
	quay.io/syedriko/tool:latest

Next, tag the image appropriately so that it can be pushed to the registry:

    podman tag localhost/latest $(oc get route default-route \
		-n openshift-image-registry \
		--template='{{ .spec.host }}')/openshift-lightspeed/acme-byok:latest

Now that you have built the image, you will need to push it into the internal
OpenShift Container Platform registry. First, go to the OpenShift web console
and then click the username in the upper-right and then click _Copy Login
Command_.

Now, copy the login command, and paste it in the web terminal. It should look
something like:

    oc login ....

== Push the Image
Now, login to the container registry with the following command:

    podman login -u admin -p $(oc whoami -t) $(oc get route default-route \
		-n openshift-image-registry --template='{{ .spec.host }}')

Lastly, push the image you just built:

    podman push blah

== Modify the OpenShift Lightspeed Configuration
Now that the image is available in an accessible container registry, you have to 
tell the OpenShift Lightspeed Operator to deploy the new RAG database alongside
the existing one.

In the OpenShift Console, click _Operators_ and then _Installed Operators_ in
the left hand navigation. Then, make sure to adjust the project dropdown to 
"All Namespaces" at the top of the screen. 

Next, click the OpenShift Lightspeed operator in the list. 

Next, click the `OLSConfig` tab, and then click the single `OLSConfig` instance
called `cluster` in the list.

Finally, select the YAML tab.

In the YAML editor, you will want to insert the following yaml segment just before
the `status` block:

    rag:
      - image: 'image-registry.openshift-image-registry.svc:5000/openshift-lightspeed/acme-byok:latest'
        indexID: vector_db_index
        indexPath: /rag/vector_db

Your full YAML should look something like:

    ...
      ols:
		...
        queryFilters:
          - name: ip-address
            pattern: '((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)\.?\b){4}'
            replaceWith: <IP-ADDRESS>
        rag:
          - image: 'image-registry.openshift-image-registry.svc:5000/openshift-lightspeed/acme-byok:latest'
            indexID: vector_db_index
            indexPath: /rag/vector_db
    status:
      conditions:

NOTE: You can define multiple RAG databases this way, if you want to add
multiple sources.

Click the blue _Save_ button.

== Wait for Lightspeed
Click the _Workloads_ navigation item on the left, then _Pods_. Next, find the
_openshift-lightspeed_ project in the dropdown (you will have to toggle the 
switch _Show default namespaces_).

Wait for the `openshift-lightspeed-...` API server pod to start and for both
containers to be ready, and for the previous deployment's containers to
terminate and disappear.

Next, let's test that it worked!